services:
  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5433:5432"   # for DBeaver / local debugging
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - timeeconomy-net

  user-db:
    image: postgres:16
    container_name: user-db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: useruser
      POSTGRES_PASSWORD: userpass
    ports:
      - "5434:5432"   # for DBeaver / local debugging
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - timeeconomy-net

volumes:
  auth-db-data:
  user-db-data:

networks:
  timeeconomy-net:
    name: timeeconomy-net   # important: fixed name for sharing
    driver: bridge